name: NHS ODS Fetch

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6AM UTC
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python ods_fetcher.py

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epraccur.csv
          git commit -m "Auto-update ODS data" || echo "No changes"
          git push
